line-length = 100
target-version = "py311"
src = ["src", "tests"]

[lint]
select = ["E", "F", "I", "B", "UP", "NPY", "RUF", "W"]
ignore = ["E203"]

[lint.isort]
known-first-party = ["alchemi", "alchemi_hsi"]
